# Generated by Django 3.2.6 on 2022-09-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0002_cropimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='node_api_key',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='nodes',
            name='thing_speak_fetch',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='nodes',
            name='user_api_key',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
