# Generated by Django 3.2.6 on 2022-09-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0003_auto_20220908_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='channel_id',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
