# Generated by Django 3.2.6 on 2022-09-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0004_nodes_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodes',
            name='last_feed_entry',
            field=models.IntegerField(null=True),
        ),
    ]
