# Generated by Django 3.2.6 on 2023-05-13 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0005_nodes_last_feed_entry'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='entry_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='feeds',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nodes',
            name='channel_id',
            field=models.IntegerField(null=True),
        ),
    ]
