# Generated by Django 3.2.6 on 2023-06-19 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nodes', '0006_auto_20230513_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='feeds',
            name='GWC',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='anthracnose',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='duration',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='event',
            field=models.BooleanField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='irrigation',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='powdery_mildew',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='feeds',
            name='root_rot',
            field=models.FloatField(default=0, null=True),
        ),
    ]
